"""
cascade_stage.py

Cascade stage related equations.
"""


def calculate_total_active_region(
    number_of_stages,
    stage_thickness
):
    """
    Calculate Total Active Region Thickness.

    Parameters
    ----------
    number_of_stages : int
        Number of cascade stages.

    stage_thickness : float
        Thickness of one cascade stage (m).

    Returns
    -------
    float
        Total active region thickness (m).
    """

    if number_of_stages <= 0:
        raise ValueError("Number of stages must be positive.")

    if stage_thickness <= 0:
        raise ValueError("Stage thickness must be positive.")

    return number_of_stages * stage_thickness

def calculate_total_voltage(
    number_of_stages,
    stage_voltage
):
    """
    Calculate Total Voltage Across the Cascade.

    Parameters
    ----------
    number_of_stages : int
        Number of cascade stages.

    stage_voltage : float
        Voltage drop across one stage (V).

    Returns
    -------
    float
        Total device voltage (V).
    """

    if number_of_stages <= 0:
        raise ValueError("Number of stages must be positive.")

    if stage_voltage <= 0:
        raise ValueError("Stage voltage must be positive.")

    return number_of_stages * stage_voltage

def calculate_total_gain(
    number_of_stages,
    gain_per_stage
):
    """
    Calculate Total Optical Gain.

    Parameters
    ----------
    number_of_stages : int
        Number of cascade stages.

    gain_per_stage : float
        Gain produced by one stage.

    Returns
    -------
    float
        Total optical gain.
    """

    if number_of_stages <= 0:
        raise ValueError("Number of stages must be positive.")

    if gain_per_stage < 0:
        raise ValueError("Gain per stage cannot be negative.")

    return number_of_stages * gain_per_stage

def calculate_total_output_power(
    number_of_stages,
    power_per_stage
):
    """
    Calculate Total Optical Output Power.

    Parameters
    ----------
    number_of_stages : int
        Number of cascade stages.

    power_per_stage : float
        Optical power generated by one stage (W).

    Returns
    -------
    float
        Total optical output power (W).
    """

    if number_of_stages <= 0:
        raise ValueError("Number of stages must be positive.")

    if power_per_stage < 0:
        raise ValueError("Power per stage cannot be negative.")

    return number_of_stages * power_per_stage